using CardsService.Domain.Entities;
using CardsService.Domain.Enums;
using FluentAssertions;

namespace CardsService.Tests.Domain;

/// <summary>
/// Testes unitários para a entidade CardDataEntity (POCO).
/// </summary>
public class CardDataEntityTests
{
    [Fact]
    public void CardDataEntity_DefaultId_IsAutoGenerated()
    {
        var card = new CardDataEntity();

        card.Id.Should().NotBeNullOrEmpty();
        card.Id.Should().HaveLength(24);
    }

    [Fact]
    public void CardDataEntity_TwoInstances_HaveDifferentIds()
    {
        var card1 = new CardDataEntity();
        var card2 = new CardDataEntity();

        card1.Id.Should().NotBe(card2.Id);
    }

    [Fact]
    public void CardDataEntity_DefaultIsActive_IsTrue()
    {
        var card = new CardDataEntity();

        card.IsActive.Should().BeTrue();
    }

    [Fact]
    public void CardDataEntity_DefaultCreatedAt_IsCloseToUtcNow()
    {
        var card = new CardDataEntity();

        card.CreatedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(5));
    }

    [Fact]
    public void CardDataEntity_DefaultUpdatedAt_IsNull()
    {
        var card = new CardDataEntity();

        card.UpdatedAt.Should().BeNull();
    }

    [Fact]
    public void CardDataEntity_DefaultUserId_IsEmpty()
    {
        var card = new CardDataEntity();

        card.UserId.Should().BeEmpty();
    }

    [Fact]
    public void CardDataEntity_SetProperties_ReflectsCorrectValues()
    {
        var card = new CardDataEntity
        {
            UserId = "user123",
            Name = "Nubank",
            Brand = CardBrand.Mastercard,
            LastFourDigits = "1234",
            CreditLimit = 5000m,
            DueDay = 10,
            IsActive = true
        };

        card.UserId.Should().Be("user123");
        card.Name.Should().Be("Nubank");
        card.Brand.Should().Be(CardBrand.Mastercard);
        card.LastFourDigits.Should().Be("1234");
        card.CreditLimit.Should().Be(5000m);
        card.DueDay.Should().Be(10);
        card.IsActive.Should().BeTrue();
    }

    [Fact]
    public void CardDataEntity_CanDeactivate_BySettingIsActiveFalse()
    {
        var card = new CardDataEntity { IsActive = true };

        card.IsActive = false;
        card.UpdatedAt = DateTime.UtcNow;

        card.IsActive.Should().BeFalse();
        card.UpdatedAt.Should().NotBeNull();
    }

    [Fact]
    public void CardDataEntity_CanUpdate_NameAndFields()
    {
        var card = new CardDataEntity { Name = "Antigo", CreditLimit = 1000m, DueDay = 5 };

        card.Name = "Novo";
        card.CreditLimit = 2000m;
        card.DueDay = 15;
        card.UpdatedAt = DateTime.UtcNow;

        card.Name.Should().Be("Novo");
        card.CreditLimit.Should().Be(2000m);
        card.DueDay.Should().Be(15);
        card.UpdatedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(5));
    }

    [Theory]
    [InlineData(CardBrand.Visa)]
    [InlineData(CardBrand.Mastercard)]
    [InlineData(CardBrand.Elo)]
    [InlineData(CardBrand.AmericanExpress)]
    public void CardDataEntity_SupportsAllBrands(CardBrand brand)
    {
        var card = new CardDataEntity { Brand = brand };

        card.Brand.Should().Be(brand);
    }
}
